name: subscriba
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  sqlite3_flutter_libs: ^0.5.18
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  provider: ^6.1.0
  collection: ^1.17.2
  sqflite_common: ^2.5.0+1
  share_plus: ^7.2.2
  file_picker: ^6.1.1
  package_info_plus: ^5.0.1
  http: ^1.2.0
  open_file: ^3.3.2
  permission_handler: ^11.3.0
  logger: ^2.1.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.1
  timeago: ^3.6.1
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: Alibaba
      fonts:
        - asset: assets/fonts/Alibaba-PuHuiTi-Regular.ttf
        - asset: assets/fonts/Alibaba-PuHuiTi-Bold.ttf
        - asset: assets/fonts/Alibaba-PuHuiTi-Heavy.ttf
        - asset: assets/fonts/Alibaba-PuHuiTi-Medium.ttf
        - asset: assets/fonts/Alibaba-PuHuiTi-Light.ttf

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
