name: Release

on:
  push:
    tags:
      - "*" # Trigger when pushing a tag like v1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "stable" # replace this with your required Flutter Version
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --split-per-abi
      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}
